version: "3.3"

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    networks:
      - whatsapp-api

networks:
  whatsapp-api:
    driver: bridge