version: "3.3"

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongodbwsp
    volumes:
      - .:/usr/src/app
    networks:
      - whatsapp-api
  mongodbwsp:
    container_name: mongodbwsp
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - whatsapp-api

networks:
  whatsapp-api:
    driver: bridge